# This is the main configuration file of your Dancer2 app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: 'Reservas::Manager'

# Layout to use
layout: 'main'
# The default layout to use for your application 
#(located in views/layouts/main.tt)

# Charset
charset: 'UTF-8'

# Session engine
session : 'Simple'

# Template engine
template: 'template_toolkit'
template_toolkit: TT
engines:
  template:
    template_toolkit:
      start_tag: '[%'
      end_tag:   '%]'

# Other Confs
logger : 'console'
log : 'debug'
show_errors : 1
startup_info : 1
warnings : 1

# Plug Ins
plugins:
    
    # Dancer2::Plugin::Auth::Extensible;
    Auth::Extensible:
        login_page_handler: 'Reservas::Manager::login_page_handler'
        permission_denied_page_handler: 'Reservas::Manager::permission_denied_page_handler'
        #disable_roles: 1
        user_home_page: '/'
        exit_page: '/'
        realms:
            config:
                provider: Config
                users:
                    - user: dave
                      username: Dave
                      pass: supersecret
                      roles:
                        - Developer
                        - Manager
                        - BeerDrinker
                    - user: bob
                      username: Bobi
                      pass: '{SSHA}+2u1HpOU7ak6iBR6JlpICpAUvSpA/zBM'
                      roles:
                        - Tester

